# Generated by Django 5.2.8 on 2025-11-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=50)),
                ('emp_id', models.IntegerField()),
                ('emp_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
